using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SEDC.PizzaApp.Domain.Models
{
    public class BaseEntity
    {
        [Key] //PK
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] //autogenerated by the db, auto increment (1, 2, 3..)
        public int Id { get; set; }
    }
}
