// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEDC.AspNet.Mvc.PizzaApp.DataAccess;

namespace SEDC.AspNet.Mvc.PizzaApp.DataAccess.Migrations
{
    [DbContext(typeof(PizzaContext))]
    partial class PizzaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SEDC.AspNet.Mvc.PizzaApp.Domain.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("SEDC.AspNet.Mvc.PizzaApp.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("SEDC.AspNet.Mvc.PizzaApp.Domain.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "Kapri.png",
                            Name = "Kapri",
                            Price = 7.0,
                            Size = 0
                        },
                        new
                        {
                            Id = 2,
                            Image = "Kapri.png",
                            Name = "Kapri",
                            Price = 7.0,
                            Size = 1
                        },
                        new
                        {
                            Id = 3,
                            Image = "Kapri.png",
                            Name = "Kapri",
                            Price = 7.0,
                            Size = 2
                        },
                        new
                        {
                            Id = 4,
                            Image = "Peperoni.png",
                            Name = "Peperoni",
                            Price = 9.0,
                            Size = 0
                        },
                        new
                        {
                            Id = 5,
                            Image = "Peperoni.png",
                            Name = "Peperoni",
                            Price = 8.0,
                            Size = 1
                        },
                        new
                        {
                            Id = 6,
                            Image = "Peperoni.png",
                            Name = "Peperoni",
                            Price = 8.0,
                            Size = 2
                        },
                        new
                        {
                            Id = 7,
                            Image = "Margarita.png",
                            Name = "Margarita",
                            Price = 10.5,
                            Size = 0
                        },
                        new
                        {
                            Id = 8,
                            Image = "Margarita.png",
                            Name = "Margarita",
                            Price = 10.5,
                            Size = 1
                        },
                        new
                        {
                            Id = 9,
                            Image = "Margarita.png",
                            Name = "Margarita",
                            Price = 10.5,
                            Size = 2
                        },
                        new
                        {
                            Id = 10,
                            Image = "Siciliana.png",
                            Name = "Siciliana",
                            Price = 6.5,
                            Size = 0
                        },
                        new
                        {
                            Id = 11,
                            Image = "Siciliana.png",
                            Name = "Siciliana",
                            Price = 9.5,
                            Size = 1
                        },
                        new
                        {
                            Id = 12,
                            Image = "Siciliana.png",
                            Name = "Siciliana",
                            Price = 9.5,
                            Size = 2
                        });
                });

            modelBuilder.Entity("SEDC.AspNet.Mvc.PizzaApp.Domain.Models.PizzaOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PizzaId");

                    b.ToTable("PizzaOrder");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            PizzaId = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            PizzaId = 4
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            PizzaId = 1
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            PizzaId = 5
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 2,
                            PizzaId = 7
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 3,
                            PizzaId = 5
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 3,
                            PizzaId = 9
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 3,
                            PizzaId = 12
                        });
                });

            modelBuilder.Entity("SEDC.AspNet.Mvc.PizzaApp.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Temnica",
                            FirstName = "Trajan",
                            LastName = "Stevkovski",
                            Phone = 1234321L
                        },
                        new
                        {
                            Id = 2,
                            Address = "Partizanska",
                            FirstName = "Vlatko",
                            LastName = "Tasevski",
                            Phone = 82363812L
                        });
                });

            modelBuilder.Entity("SEDC.AspNet.Mvc.PizzaApp.Domain.Models.Order", b =>
                {
                    b.HasOne("SEDC.AspNet.Mvc.PizzaApp.Domain.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SEDC.AspNet.Mvc.PizzaApp.Domain.Models.PizzaOrder", b =>
                {
                    b.HasOne("SEDC.AspNet.Mvc.PizzaApp.Domain.Models.Order", "Order")
                        .WithMany("PizzaOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEDC.AspNet.Mvc.PizzaApp.Domain.Models.Pizza", "Pizza")
                        .WithMany("PizzaOrders")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
